const CREDIT_MIN = 10000;
const CREDIT_MAX = 10000000;
const CREDIT_DEFAULT = CREDIT_MIN;
const CREDIT_STEP = 1000;
const PERIOD_MIN = 12;
const PERIOD_MAX = 360;
const PERIOD_DEFAULT = PERIOD_MIN;
const PERIOD_STEP = 1;
const INTEREST_MIN = 0.0;
const INTEREST_MAX = 100.0;
const INTEREST_DEFAULT = 10.0;
const INTEREST_STEP = 0.1;


const constants = {
  CREDIT_MIN,
  CREDIT_MAX,
  CREDIT_STEP,
  CREDIT_DEFAULT,
  PERIOD_MIN,
  PERIOD_MAX,
  PERIOD_DEFAULT,
  PERIOD_STEP,
  INTEREST_MIN,
  INTEREST_MAX,
  INTEREST_DEFAULT,
  INTEREST_STEP,
};

export default constants;